from single_linked_list import SingleLinkedList
inst_SLL= SingleLinkedList()
inst_SLL.create_node_sll_unshift(5)
inst_SLL.create_node_sll_unshift(2)
inst_SLL.create_node_sll_unshift(11)
inst_SLL.create_node_sll_unshift(6)
print('1. Agregar un elemento al principio de la lista')
inst_SLL.create_node_sll_unshift(4)
inst_SLL.show_list()
print('2. Agregar un elemento al final de la lista')
inst_SLL.create_node_sll_ends('Pedro')
inst_SLL.show_list()
print('3. Eliminar el primer elemento de la lista simplemente enlazada' )
inst_SLL.shift_node_sll()
inst_SLL.show_list()
print('4. Eliminar el ultimo elemento de la lista simplemente enlazada')
inst_SLL.delete_node_sll_pop()
inst_SLL.show_list()
print('5. Obtener el tamaño de la lista')
print(inst_SLL.show_length_node())
print('6. Buscar un elemento en la lista y devolver su posicion')
inst_SLL.get_node_index(2)
print('7. Devolver el elemento en una determinada posición de la lista')
inst_SLL.get_node_value(2)
print('8. Invertir la lista')
inst_SLL.revert_node_list()
inst_SLL.show_list()
print('9. Eliminar todos los elementos de la lista simplemente enlazada')
inst_SLL.remove_all_nodes()
inst_SLL.show_list()
#Vuelvo a ingresar datos
inst_SLL.create_node_sll_unshift(5)
inst_SLL.create_node_sll_unshift(2)
inst_SLL.create_node_sll_unshift(11)
inst_SLL.create_node_sll_unshift(6)
print('10. Ordenar elementos de la lista simplemente enlazada')
inst_SLL.show_order_list()
print('11. Eliminar un elemento en una posición determinada de la lista simplemente enlazada.')
inst_SLL.remove_node(2)
inst_SLL.show_list()
print('12. Insertar un elemento en una posición determinada de la lista simplemente enlazada.')
inst_SLL.insert_node(10,3)
inst_SLL.show_list()
print('13. Actualizar el valor de un elemento en una posición determinada de la lista simplemente enlazada.')
inst_SLL.update_node_value(2,'Çapibara')
inst_SLL.show_list()
print('14. Comprobar si la lista simplemente enlazada está vacía.')
inst_SLL.verify_list()

