from binary_tree import BinaryTree
tree = BinaryTree
root = BinaryTree(12)
root.insert(root,BinaryTree(8))
root.insert(root,BinaryTree(18))
root.insert(root,BinaryTree(6))
root.insert(root,BinaryTree(10))
root.insert(root,BinaryTree(2))
root.insert(root,BinaryTree(7))
root.insert(root,BinaryTree(9))
root.insert(root,BinaryTree(10))
root.insert(root,BinaryTree(11))
root.insert(root,BinaryTree(15))
root.insert(root,BinaryTree(20))
root.insert(root,BinaryTree(14))
root.insert(root,BinaryTree(17))
root.insert(root,BinaryTree(19))
root.insert(root,BinaryTree(21))

root.print_tree(root)
root.minValue(root)
root.maxValue(root)
