if __name__ == '__main__':
    from double_linked_list import DoubleLinkedList
    inst_dll = DoubleLinkedList()
    inst_dll.add_node_at_start(1)
    inst_dll.add_node_at_start(2)
    inst_dll.add_node_at_start(3)
    inst_dll.add_node_at_start(7)
    inst_dll.add_node_at_start(5)
    inst_dll.add_node_at_end(6)
    inst_dll.add_node_at_end(7)
    inst_dll.add_node_at_end(8)
    inst_dll.print_list()
    inst_dll.add_node_in_position(4,10)
    inst_dll.print_list()
    inst_dll.remove_node_by_position(1)
    inst_dll.print_list()
    inst_dll.remove_node_by_position(8)
    inst_dll.print_list()
    inst_dll.remove_node_by_value(2)
    inst_dll.print_list()
    inst_dll.get_node_at_index(6)
    inst_dll.get_node_by_value(6)
    inst_dll.update_node_at_index(2,12)
    inst_dll.print_list()
    inst_dll.update_node_by_value(1,707)
    inst_dll.print_list()
    inst_dll.reverse()
    inst_dll.print_list()
    inst_dll.sort_asc()
    inst_dll.print_list()
    inst_dll.has_duplicates()
    inst_dll.has_duplicates_with_information()
    inst_dll.calculate_complexity(inst_dll.add_node_at_end)